name: Auto Scan + Send

on:
  schedule:
    - cron: "*/10 * * * *"   # هر ۱۰ دقیقه
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install telethon python-dotenv requests beautifulsoup4

      - name: Run scraper
        run: |
          python scraper/scraper.py

      - name: Commit updated files
        run: |
          git config --global user.email "github-actions@github.com"
          git config --global user.name "GitHub Actions"
          git add .
          git commit -m "Auto update" || echo "No changes"
          git push || echo "Nothing to push"

      - name: Run bot
        env:
          API_ID: ${{ secrets.API_ID }}
          API_HASH: ${{ secrets.API_HASH }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        run: |
          python bot.py
