name: Telegram Bot Sender

on:
  schedule:
    - cron: "*/10 * * * *"   # هر ۱۰ دقیقه
  workflow_dispatch:         # اجرای دستی

jobs:
  send:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install telethon python-dotenv

      - name: Run bot
        env:
          API_ID: ${{ secrets.API_ID }}
          API_HASH: ${{ secrets.API_HASH }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        run: |
          python bot.py
